# Generated by Django 4.2.6 on 2025-07-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5, unique=True)),
                ('nama', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=5, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HasilDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_kepercayaan', models.FloatField(help_text='Nilai akhir kepercayaan setelah perhitungan DS')),
                ('diagnosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_ds', to='sp_kanker_diagnosa_app.diagnosa')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.penyakit')),
            ],
        ),
        migrations.CreateModel(
            name='GejalaDiagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gejala_terpilih', to='sp_kanker_diagnosa_app.diagnosa')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.gejala')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='pasien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosa', to='sp_kanker_diagnosa_app.pasien'),
        ),
        migrations.CreateModel(
            name='BasisPengetahuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot_kepercayaan', models.FloatField(help_text='Contoh: 0.6 untuk kepercayaan 60%')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.gejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.penyakit')),
            ],
            options={
                'unique_together': {('gejala', 'penyakit')},
            },
        ),
    ]
