# Generated by Django 4.2.6 on 2025-07-18 14:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.CharField(max_length=100)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROSES', 'Dalam Proses'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], default='PROSES', max_length=10)),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan dari diagnosa')),
                ('total_gejala', models.PositiveIntegerField(default=0, help_text='Jumlah gejala yang dipilih')),
            ],
            options={
                'verbose_name': 'Diagnosa',
                'verbose_name_plural': 'Diagnosa',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Gejala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('kategori', models.CharField(choices=[('UMUM', 'Gejala Umum'), ('KHUSUS', 'Gejala Khusus'), ('LANJUTAN', 'Gejala Lanjutan')], default='UMUM', max_length=20)),
                ('pertanyaan', models.TextField(help_text='Pertanyaan untuk mengidentifikasi gejala')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gejala',
                'verbose_name_plural': 'Gejala',
                'ordering': ['kategori', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=10)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('umur', models.PositiveIntegerField(blank=True, help_text='Umur dalam tahun', null=True)),
                ('riwayat_keluarga', models.TextField(blank=True, help_text='Riwayat kanker dalam keluarga')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasien',
                'verbose_name_plural': 'Pasien',
                'ordering': ['-dibuat'],
            },
        ),
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('tingkat_keganasan', models.CharField(choices=[('RENDAH', 'Rendah'), ('SEDANG', 'Sedang'), ('TINGGI', 'Tinggi')], default='SEDANG', max_length=20)),
                ('pengobatan', models.TextField(blank=True)),
                ('pencegahan', models.TextField(blank=True)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Penyakit',
                'verbose_name_plural': 'Penyakit',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='PerhitunganDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_function', models.DecimalField(decimal_places=4, help_text='Mass function untuk gejala-penyakit ini', max_digits=5)),
                ('belief_function', models.DecimalField(decimal_places=4, help_text='Belief function', max_digits=5)),
                ('plausibility_function', models.DecimalField(decimal_places=4, help_text='Plausibility function', max_digits=5)),
                ('langkah_perhitungan', models.TextField(help_text='Detail langkah perhitungan')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diagnosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perhitungan_ds', to='sp_kanker_diagnosa_app.diagnosa')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.gejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.penyakit')),
            ],
            options={
                'verbose_name': 'Perhitungan DS',
                'verbose_name_plural': 'Perhitungan DS',
                'ordering': ['diagnosa', 'gejala'],
            },
        ),
        migrations.AddField(
            model_name='diagnosa',
            name='pasien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosa', to='sp_kanker_diagnosa_app.pasien'),
        ),
        migrations.CreateModel(
            name='HasilDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_kepercayaan', models.DecimalField(decimal_places=4, help_text='Nilai akhir kepercayaan setelah perhitungan DS', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('nilai_ketidakpercayaan', models.DecimalField(decimal_places=4, help_text='Nilai ketidakpercayaan', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('nilai_uncertainty', models.DecimalField(decimal_places=4, help_text='Nilai ketidakpastian (uncertainty)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('ranking', models.PositiveIntegerField(help_text='Peringkat hasil diagnosa')),
                ('rekomendasi', models.TextField(blank=True, help_text='Rekomendasi berdasarkan hasil diagnosa')),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diagnosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_ds', to='sp_kanker_diagnosa_app.diagnosa')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.penyakit')),
            ],
            options={
                'verbose_name': 'Hasil Dempster-Shafer',
                'verbose_name_plural': 'Hasil Dempster-Shafer',
                'ordering': ['diagnosa', 'ranking'],
                'unique_together': {('diagnosa', 'penyakit')},
            },
        ),
        migrations.CreateModel(
            name='GejalaDiagnosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tingkat_keparahan', models.CharField(choices=[('RINGAN', 'Ringan'), ('SEDANG', 'Sedang'), ('BERAT', 'Berat')], default='SEDANG', max_length=20)),
                ('durasi', models.CharField(blank=True, help_text='Berapa lama gejala muncul', max_length=50)),
                ('catatan', models.TextField(blank=True, help_text='Catatan tambahan untuk gejala ini')),
                ('dipilih_pada', models.DateTimeField(auto_now_add=True)),
                ('diagnosa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gejala_terpilih', to='sp_kanker_diagnosa_app.diagnosa')),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sp_kanker_diagnosa_app.gejala')),
            ],
            options={
                'verbose_name': 'Gejala Diagnosa',
                'verbose_name_plural': 'Gejala Diagnosa',
                'unique_together': {('diagnosa', 'gejala')},
            },
        ),
        migrations.CreateModel(
            name='BasisPengetahuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bobot_kepercayaan', models.DecimalField(decimal_places=4, help_text='Nilai antara 0.0000 - 1.0000 (Contoh: 0.6000 untuk kepercayaan 60%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('bobot_ketidakpercayaan', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Nilai ketidakpercayaan (1 - bobot_kepercayaan)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))])),
                ('sumber_referensi', models.CharField(blank=True, help_text='Sumber referensi untuk bobot ini', max_length=200)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('diperbarui', models.DateTimeField(auto_now=True)),
                ('gejala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basis_pengetahuan', to='sp_kanker_diagnosa_app.gejala')),
                ('penyakit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basis_pengetahuan', to='sp_kanker_diagnosa_app.penyakit')),
            ],
            options={
                'verbose_name': 'Basis Pengetahuan',
                'verbose_name_plural': 'Basis Pengetahuan',
                'ordering': ['penyakit', 'gejala'],
                'unique_together': {('gejala', 'penyakit')},
            },
        ),
    ]
