# Generated by Django 4.2.6 on 2025-07-19 08:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_kanker_diagnosa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gejaladiagnosa',
            name='bobot_pengguna',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Bobot kepercayaan pengguna terhadap gejala (0.0000 - 1.0000)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0000')), django.core.validators.MaxValueValidator(Decimal('1.0000'))]),
        ),
    ]
