# Generated by Django 4.2.6 on 2025-07-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_kanker_diagnosa_app', '0002_gejaladiagnosa_bobot_pengguna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosa',
            name='nama_user',
        ),
    ]
